### PR TITLE
Multi node hanging problem fix

### PR DESCRIPTION
**Pull request by MSementsov-Ibk**
When selecting a bunch of nodes in a dragging them around randomly, some nodes tend to get stuck on other nodes.

Signed-off-by: Michael Sementsov <michael.sementsov@ibykus.de>

### CODE REVIEW

**Comment by nprigour** [comment]
Hi @MSementsov-Ibk,

Just to clarify with the term nodes you mean i.e. vertices of a feature of type polygon, multipolygon etc  or just single point features on a point layer?

**Comment by MSementsov-Ibk** [comment]
Hi @nprigour,

yes I do mean vertices, sorry for the confusion.

**Comment by nprigour** [comment]
Can you clarify the following:
- the problem occurs when edit geometry tool is activated?
- the problem may occur when selecting multiple vertices of the same feature or of different features?
- should a certain snapping mode be active (or it is irrelevant)?

I tried to replicate the problem by dragging around some feature vertices while in edit mode but without  luck.

- Do you have an example shp layer (populated with features) that can be used to demonstrate the problem?

**Comment by MSementsov-Ibk** [comment]
Sorry, I'm pretty bad at explaining things, so I made a video demonstrating the issue. 

[current](https://youtu.be/ON3G_ycxEoA)

[fixed](https://youtu.be/AYtWJ5yVYoA)

I hope that helps.

**Comment by nprigour** [comment]
Hi @MSementsov-Ibk 
I have some problems with loading the supplied shp file. Can you add to the zip all the accompanied files (.dbf, .prj, .fix etc.)?

**Comment by MSementsov-Ibk** [comment]
@nprigour 
Sure, here you go. That's all the files I used.
[all_test.zip](https://github.com/locationtech/udig-platform/files/2454760/all_test.zip)

**Comment by nprigour** [comment]
OK issue replicated. It seems that the problem occurs when selecting and moving coordinates of a feature that are very close one to the other.
Although I did not exhaustively reviewed the altered code from a few UI testing on the Map Editor it seems that after applyig the PR moving of features works pretty fine.

Note that If considered for merge code style must be corrected.

**Comment by MSementsov-Ibk** [comment]
Formatting applied.

**Comment by fgdrf** [comment]
Looks like the whole file was re-formated which hides modification for this bugfix a bit. However, thanks for the fix

**Comment by nprigour** [comment]
Since the formatting was applied as a separate commit we can infer the exact changes if we check the PR.
However @MSementsov-Ibk it would be good to apply formatting only to the part of the file you modify. If using eclipse this can be achieved by selecting only the modified fragment of code in the editor and then selecting source-->format from the popup menu  :)

**Pull request merged**
