### PR TITLE
#517 retires osmbox & jconsole (GeoScript) module

### PR DESCRIPTION
**Pull request by fgdrf**
due to incompatibility of jts versions

Signed-off-by: Frank Gasdorf <fgdrf@users.sourceforge.net>

### CODE REVIEW

**Comment by sschulz92** [comment]
Why did you move all sources to `archive` instead of complete deletion? Since we are using Git, you can easily revert the deletion in case you decide to use it later on again. I doubt that this will happen to be honest. In case you need something similar in the future, you will write a new feature with state-of-the-art tools at this time.

**Comment by fgdrf** [comment]
> Why did you move all sources to `archive` instead of complete deletion? Since we are using Git, you can easily revert the deletion in case you decide to use it later on again. I doubt that this will happen to be honest. In case you need something similar in the future, you will write a new feature with state-of-the-art tools at this time.

If these are still visible it might be easier to involve others. I guess if they are deleted these are out of mind. And IMHO the jconsole is a great feature to allow scripting with datasources and map but right now the effort was to big from me to untie it from omsbox. However I personally believe that [GeoScript](https://geoscript.net) intergration should be enabled again in the near future.

That said, @moovida what do you think about collaborating on this topic?

**Comment by moovida** [comment]
Hi @fgdrf , as much as I wish to, I do not have any project that involves uDig at the current time. With HM and SMASH I have 0 free time left to help on this. I am really sorry. I also believe a GIS needs to have spatial analysis features and scripting, but that doesn't help as a thought alone.

Also, the last times I downloaded the current uDig version, it wasn't usable on my mac.

**Comment by fgdrf** [comment]
> Hi @fgdrf , as much as I wish to, I do not have any project that involves uDig at the current time. With HM and SMASH I have 0 free time left to help on this. I am really sorry. I also believe a GIS needs to have spatial analysis features and scripting, but that doesn't help as a thought alone.
@moovida don't mind, I totally understand you situation ass I heared on #FOSS4G your are involved in more than mentioned projects.

> Also, the last times I downloaded the current uDig version, it wasn't usable on my mac.

Not that good, however are you kind to report any issue you stumbling about. Tought one here that I do not have a Mac anymore to verify a fix is working on that platform.

**Pull request merged**
