### PR TITLE
change visibility of category finder methods in ToolManager to public and made them final 

### PR DESCRIPTION
**Pull request by nprigour**
change visibility of category finder methods in ToolMnager to public and made them final to prohibit their subclassing.

Signed-off-by: Nikolaos Pringouris <nprigour@gmail.com>

### CODE REVIEW

**Comment by fgdrf** [comment]
Good idea, wondering why we should not add these to IToolManager as well. Then there is no need to cast to ToolManager e.g. in ToolProxy anymore..

**Comment by nprigour** [comment]
Hi @fgdrf, 
I also do not see any blocking reason to your proposal. Do you want to proceed with this modification in the present PR?

**Comment by fgdrf** [comment]
Providing a pull request for your branch to pull it into interface ..

**Comment by fgdrf** [comment]
started a build to get feedback https://ci.eclipse.org/udig/job/uDig-PR/40/

**Comment by nprigour** [comment]
It seems that everything is OK!

**Comment by fgdrf** [comment]
> 
> 
> It seems that everything is OK!

Hmm, not really, The build infrastructure is quite slow and several builds haven't finished successfully. However, on my machine it works, compilation and tests were fine. I'll merge ..

Many thanks for your contribution and collaboration!

**Comment by nprigour** [comment]
Indeed it seems that there are some problems with jenkins (or the machine it runs) because I also experienced problems while trying to view the progress of the build!

**Pull request merged**
