### PR TITLE
compare metrics fix (origin PR was #224)

### PR DESCRIPTION
**Pull request by fgdrf**
for details see discussion in #224

### CODE REVIEW

**Comment by fgdrf** [comment]
triggered a build to get Feedback for regressions : https://ci.eclipse.org/udig/job/uDig-PR/17

I assume these coming from registered RenderMetric in plugin.xml in test-bundle and are used for all other tests as well. It might help to register them dynamically via plugin-API only for specific test cases. 

Need to investigate on this if build is finished

**Comment by fgdrf** [comment]
Looks like a NPE causes failures:
```
java.lang.NullPointerException: null
	at org.locationtech.udig.project.tests.support.TestMapDisplay.getWidth(TestMapDisplay.java:31)
	at org.locationtech.udig.project.internal.render.impl.RenderMetricsSorter.rate(RenderMetricsSorter.java:186)
	at org.locationtech.udig.project.internal.render.impl.RenderMetricsSorter.compareMetrics(RenderMetricsSorter.java:132)```

For more details, have a look at [test results](https://ci.eclipse.org/udig/job/uDig-PR/17/testReport/)

**Comment by fgdrf** [comment]
last commit fixed test failures (https://ci.eclipse.org/udig/job/uDig-PR/18)

**Comment by nprigour** [comment]
So @fgdrf  ihas the problem been solved?

**Comment by fgdrf** [comment]
Yes, fixed MapTests class and  initialized Dimention if it was null

**Comment by fgdrf** [comment]
Build result is fine : https://ci.eclipse.org/udig/job/uDig-master-CI/129

**Pull request merged**
