### PR TITLE
Solve deprecation of ChangeCRSCommand

### PR DESCRIPTION
**Pull request by sschulz92**
Which ends in the deletion of BasicCommandFactory also

### CODE REVIEW

**Comment by sschulz92** [comment]
I would like to ask for a review on this also @fgdrf :D

**Comment by fgdrf** [comment]
This is related to #436 which I can update after this change.

so thanks for providing this cleanup of deprecated code. Wondering if its worth to add a hint in ‚What‘s new’ pages which Classes are not available anymore and what to use instead as a SDK user. Would you add a few lines?

I can have a look at other changes we have merged already

**Comment by sschulz92** [comment]
> Wondering if its worth to add a hint in ‚What‘s new’ pages which Classes are not available anymore and what to use instead as a SDK user. Would you add a few lines?

I did, it's okay like this?

**Review by fgdrf — APPROVED** [review]
Great, thanks for your effort

**Review by fgdrf — APPROVED** [review]

**Pull request merged**
