### PR TITLE
[docs] updated 'what is new' pages

### PR DESCRIPTION
**Pull request by fgdrf**
* adds What is new page for 2.3
* enhances What is new page for 2.2

Change-Id: Ie9d5e597833ae5d7fc66defa97388e404d4c2dd2
Signed-off-by: Frank Gasdorf <fgdrf@users.sourceforge.net>

### CODE REVIEW

**Comment by fgdrf** [comment]
@egouge Would you be kind and review the user-doc changes?

**Comment by egouge** [comment]
I can - what am I looking for?

**Comment by fgdrf** [comment]
Just prove-reading the docs (rst) files and which is the source of user
docs. This would in terms of wording and understanding. Build with tests is
fine (see workflow check). If you like to see the output, just follow the
readme in docs folder how to run sphinx build (requires python)

Thanks in advance!

Emily ***@***.***> schrieb am Do. 20. Mai 2021 um 22:38:

**Review by egouge — APPROVED** [review]
I fixed one link issue but otherwise I think it's fine.

**Comment by fgdrf** [comment]
@egouge Thanks you! Merged already

**Pull request merged**
