### PR TITLE
Fix for decimal CRSes

### PR DESCRIPTION
**Pull request by d3m0n1c**
Fix for decimal LatLon CRSes (in our case NDS).

Was taken from here: http://lists.refractions.net/pipermail/udig-devel/2009-April/014658.html
@hwellmann, can I use your code?

### CODE REVIEW

**Comment by hwellmann** [comment]
Sure, you're welcome to use my code snippet under EPL.

**Comment by d3m0n1c** [comment]
@fgdrf how this ip-validation can be passed?

**Comment by fgdrf** [comment]
please commit with signed by option (-s). For detail have a look at the blog-post http://udig-news.blogspot.de/2015/12/tipps-and-tricks-creating-pull-requests.html

**Comment by fgdrf** [comment]
@hwellmann Thanks for your contribution aggreement.

**Pull request merged**
