### PR TITLE
Feature to hide renderer job in progress views

### PR DESCRIPTION
**Pull request by fgdrf**
if the job is a system job, its not displayed in progress-view anymore for default. In Progress Views its possible to allow to show system jobs (and sleeping jobs) again

grafik

to configure it just use `.options` files it installation folder with 

`org.locationtech.udig.project/HIDE_RENDER_JOB=true`

is present.

Default behavior is as before : Jobs are still shown in Progress-View

### CODE REVIEW

**Comment by olsmn** [comment]
Cool feature :)
Now one may choose to treat renderer Jobs as system jobs and so avoid the flickering caused by continuously showing "Rendering Map" in Progress View e.g. with streamed updates on Layer Data source.

**Comment by olsmn** [comment]
However the first commit concerning pom.xml seems to be unrelated to the topic ...

**Comment by fgdrf** [comment]
> However the first commit concerning pom.xml seems to be unrelated to the topic ...

you are right, seems I've mixed up changes from two different branches. I'll cleanup this pull-request and remove pom.xml from this changeset

**Comment by olsmn** [comment]
Now that looks good :)

**Pull request merged**
