### PR TITLE
Fixes #431 welcome page link issues

### LINKED ISSUE #431: Links to help from Intro/Welcome page are not working
From this Welcome view
grafik

the links to 
* Overview,
* Tutorials, and
* What's new are obviously wrong:

grafik

Having a look into source: the help-Ids using still net.refractions.udig namespace.

### PR DESCRIPTION
**Pull request by fgdrf**

### CODE REVIEW

**Comment by fgdrf** [comment]
@dwadler this pull request fixes welcome page(s), would you give it a try?

**Comment by dwadler** [comment]
@fgdrf I'm not sure how to test this or how the help mechanism works.

I copied your updated root.xml into my installation e:\udig2.2.0.RC1\plugins\org.locationtech.udig_2.2.0RC1\intro.

Clicking on the Overview link in the right panel brings up the help with the message "Topic not found". when I hover over "uDig Overview" in the table of contents, it shows the URL:
http://127.0.0.1:52566/help/topic/org.locationtech.udig.help/EN/uDig%20Overview.html?cp=0_0

I tried changing the text "Get an overview of uDig" in root.xml but the change doesn't appear in the right pane of uDig after restarting it. Is root.xml built into some jar during the build process?

Where does the uDig help exist? I don't see any file "uDig overview.html" anywhere

**Comment by dwadler** [comment]
@fgdrf When I poke inside org.locationtech.udig.help_2.2.0.RC1, I see nl subdirectories for de, es, eu, fr, it but no 'en' directory.

If I startup uDig with -nl de and click on the top item in the right panel, it does bring up the help in German. If I click on "Home" and then English, it links to the English help on http://udig.refractions.net/confluence/display/EN/home which has the uDig User Guide.

**Comment by fgdrf** [comment]
> 
> 
> @fgdrf When I poke inside org.locationtech.udig.help_2.2.0.RC1, I see nl subdirectories for de, es, eu, fr, it but no 'en' directory.
> 
> If I startup uDig with -nl de and click on the top item in the right panel, it does bring up the help in German. If I click on "Home" and then English, it links to the English help on http://udig.refractions.net/confluence/display/EN/home which has the uDig User Guide.

Thanks for check that the problems exists. 

the default is used from intro folder (root of the bundle) whereas localized content is hosted in nl/<langguage>/intro if present.

**Pull request merged**
