### PR TITLE
upgrade to geotools 19.2 and java 8

### PR DESCRIPTION
**Pull request by nprigour**
pull request addresses the following:

- upgrade to latest stable geotols version (19.0)
- upgrade to java 8 (required for geotools 15.x and above)

see also issue #278

Signed-off-by: Nikolaos Pringouris <nprigour@gmail.com>

### CODE REVIEW

**Comment by fgdrf** [comment]
Great, product build is fine! I run a Pull [request Build](https://ci.eclipse.org/udig/job/uDig-PR/8) and found following errors in log for test some runs:

`Missing requirement: uDig 2.1.0.201804281546 (org.locationtech.udig-product 2.1.0.201804281546) requires 'config.a.jre.javase [1.6.0]' but it could not be found`

I'm still investigating for a proper Tycho setup .. 

@nprigour I guess I can provide a pull for your branch soon.

**Comment by fgdrf** [comment]
Looks like https://demo.geo-solutions.it/geoserver (used in test cases) is down blockes executions. Investigation why `CatalogTestUtils.assumeNoConnectionException` doesn't work as expected. It should skip test executions if an exception occurs ..

**Comment by fgdrf** [comment]
Unit-Test `org.locationtech.udig.libs.tests.GeoToolsTest` requires an updated to assert 19 rather than 14 ;)

**Comment by nprigour** [comment]
So is that only? Would you do make the change or should I do it?

**Comment by fgdrf** [comment]
Created a pull request for your feature branch, for details see https://github.com/nprigour/udig-platform/pull/9

**Comment by fgdrf** [comment]
Run a full build and only one test failed regulary, going to have a look into it:

```
Failed tests:
  IssuesManagerTest.testRemoveIssues:78 expected:<10> but was:<11>
```

**Comment by fgdrf** [comment]
added another commit which fixes IssuesManagerTest ;)

**Comment by fgdrf** [comment]
BTW, you can trigger a job https://ci.eclipse.org/udig/job/uDig-PR/ if you log-in with your Eclipse committer account. 
I started https://ci.eclipse.org/udig/job/uDig-PR/9 for this pull request (#279)

**Comment by nprigour** [comment]
Sorry @fgdrf  but I do not have an Eclipse committer account just a simple account :)

**Comment by fgdrf** [comment]
.. and once if finished you can download archived artifacts for the last build ;)

**Comment by fgdrf** [comment]
@nprigour Try with your Eclipse Account, if it works fine, if not we can address it

**Comment by nprigour** [comment]
I can view the page you mentioned but just that. It seems that I do not have any additional rights to trigger jobs or builds!

**Comment by fgdrf** [comment]
https://ci.eclipse.org/udig/job/uDig-PR/10/ made it, 3 test-failures I haven't seen before we can address

**Comment by fgdrf** [comment]
I guess these two failing test comming from GeoTools and its thirdparty dependencies update:

* org.locationtech.tools.geometry.split.RingExtractorTest.testEndLineFinishOnEdge
* org.locationtech.tools.geometry.split.RingExtractorTest.testEndLineFinishOnEdge2Rings

Maybe expectations are not valid anymore. @nprigour Do you have any idea?

**Comment by nprigour** [comment]
Hi @fgdrf,
I tried to debug a bit by running the tests from within eclipse (no udig application is needed for them) and the result was that only:

- org.locationtech.tools.geometry.split.RingExtractorTest.testEndLineFinishOnEdge

failed. The other one completed successfully. Really strange!! Additionally, all these tests seem to depend only on JTS library by vividsolutions which is quite stable. The version currently used is v1.14 while our previous release (that depend on geotools14.1) utilized v1.13.
I will try to investigate a bit further the reason of failure.
Can we verify somehow that jenkins uses indeed jts1.14?

**Comment by nprigour** [comment]
On the other hand now that I run it from mvn  command line I experienced the opposite behavior

- org.locationtech.tools.geometry.split.RingExtractorTest.testEndLineFinishOnEdge2Rings

fails
while
org.locationtech.tools.geometry.split.RingExtractorTest.testEndLineFinishOnEdge

- org.locationtech.tools.geometry.split.RingExtractorTest.testEndLineFinishOnEdge
succeeds.
Really weird! Is there some inderdependancy that may affect one the other?
I tried also to run them from within eclipse each one in separate execution and both pass succesfully!!!!

**Comment by nprigour** [comment]
Investigation a bit further it seems that the problem is caused by org.locationtech.tools.geometry.split.RingExtractorTest.testpolygonizer() test which runs between the 2 aformentioned tests. If you mark this as Ignore then all tests defined in  RingExtractorTest pass succesfully. 
I cannot undestand why this happens as well as what this testpolygonizer() method actually tests. It has no assertions or any other junit specific code. It seems that the test does not tests something!!
If you more expertise in junit and have any idea please advise.

**Comment by fgdrf** [comment]
@mpazos Can you help here? I guess RingExtractor has been implemented for 1.3.0

**Comment by fgdrf** [comment]
I've tested with maven 3.5 on my local box but couldn't get any test failing. 

I found out that on Jenkins Instance jdk [1.8.0_163-b12](https://ci.eclipse.org/udig/job/test-versions/jdk=jdk1.8.0-latest/1/console) is used (latest java 8) while I use oracle jdk 1.8.0_152 at the moment of writing. Going to test with openjdk ..

**Comment by nprigour** [comment]
Hi @fgdrf,
In my local box I was using maven 3.3.9 and oracle jdk 1.8.0_144 and these specific RingExtractor tests fail. Based on your previous comment I tried the following:

- upgrade to maven to v3.5.3 and keep the same java (oracle jdk 1.8.0_144) --> the test still fails
- keep maven v3.3.9 and update to latest jdk (oracle jdk 1.8.0_171) --> the test still fails 
- upgrade to maven to v3.5.3 and update also to latest jdk (oracle jdk 1.8.0_171) --> the test  succeeds 👍 
The whole thing seems pretty weird!

**Comment by nprigour** [comment]
by the way a couple of days ago geotools v19.1 was released. Maybe it is worth to update to this version before proceeding with this!

**Comment by fgdrf** [comment]
@nprigour 19.1 rather than 19.0 makes sense, I guess the effort isn't that much to upgrade from 19.0. I assume transitive dependencies haven't changed since, except of MySQL driver

Release notes for GeoTools https://osgeo-org.atlassian.net/secure/ReleaseNote.jspa?projectId=10001&version=16723

+1 from my side, would you rebase and upgrade?

**Comment by nprigour** [comment]
I rebase and forced push to resolve conficts with master branch due to previous PR commits.
I will check upgrade to 19.1 at a second step the coming days since from a quick check it seems  not so straightforward (it seems there are some issues with getting all the necessary dependancies).

**Comment by nprigour** [comment]
Hi @fgdrf ,

I just performed the changes needed to upgrade to geotools 19.1. 
Actually it waw straightforward by changing the geotools version to 19.1 to pom-libs.xml  and performing some classpath updates all witihn org.locationtech.udig.libs plugin.
after executing:
`mvn clean install -f pom-libs.xml`
within the aformentioned pluging all needed jars were retrieved succesfully.
The issues I reported yesterday were related to using a latest version of maven (v3.5.3) for executing the above command. When doing this for some reason warning messages appeared mentioning that  transitivie dependencies of certain geotools packages could not be available (see screenshot below). But I assume the same problem would occur with v19.0
 
default

using an older version of of maven (3.3.9) as I did until recently retrieval of needed jars completed without problems.

Now the only issue that still stands for approving this PR is the problem with the jenkins failing the test related to RingExtractor which fails randomly without an obvious reason.

**Comment by nprigour** [comment]
Hi @fgdrf ,
Investigating a bit further with the faling RingExtractorTest I figure out that the RingExtractor() class utilizes JTS Polygonizer() which seems to have some modifications in JTS1.14 compared to previously used JTS1.13 resulting in remaining lines during Ring extraction being computed differently.
In my opinion there is no point to try and figure out which version of JTS provides the correct behavior since the issue is with the remaining lines. Suggestion is either to ignore this tests or slightly modified them (by removing some linesstring that their existence is expected to be validated) in order the test to execute successfully

**Comment by fgdrf** [comment]
@nprigour Are you takling about following changes?

* https://github.com/locationtech/jts/commit/6fb614c7510ebd4f65e8dd5afa119bbf49c6d809
* https://github.com/locationtech/jts/commit/592b21c7a5f98cb82f6e9060a66561257e8d2ff4
* https://github.com/locationtech/jts/commit/4e3d0ddbd4b60d8f5895f9e908cb8f72c24efe2f

Sadly we cannot compare tags / branches on locationtech github. Maybe we can compare two Tags in old SVN Repository https://sourceforge.net/p/jts-topo-suite/code/HEAD/tree/tags/

My impression is that we have to care about the tests and I expect we have to change RingExtractor itself .. we'll see

**Comment by nprigour** [comment]
@fgdrf ,
Are you sure that these tests always passed when using geotools 14.1 and jts1.13? The strange thing is that the result of execution seems to produce random output in what concerns the remaininig lines of RingExtractorion while the actual rings are extracted correctly always. Therefore I am not sure for 2 things:

1. what exactly these 2 tests (testEndLineFinishOnEdge, testEndLineFinishOnEdge2Rings) actually evaluate. Do we care about the remaining lines (which by the way may be invalid) or only for the rings? 
2. how the expectedParts (partA, partB, partC etc) were computed and provided for the test at the very first time. Di the author provide their values applying some scientific computations or just used output of the RingExtractor as feedback on the proper values to put there. 

I.e. I can rewrite the tests so that they always pass by excluding certain expectedParts  or changing them to match the produced RingExtractor output.  If i.e. you comment out lines 242, 266 of RingExtractorTest then the test will always succeed. All in all, in order to conclude the present PR I see 2 options:

1. do the aformentioned change (comment out lines 242, 266) in the present pull request (my suggestion) or 
2. set these 2 tests with an ignore annotation and check them more thoroughly in another PR (to be honest I think there is no serious reason to do so unless we conclude that RingExtractor does not work the way we expect)
Please provide your feedback on how to proceed

**Comment by nprigour** [comment]
So @fgdrf how do you suggest to proceed?

**Comment by nprigour** [comment]
Hi @fgdrf 
We must see how we address this PR and whether we are going to merge it? Since it introduces a major number of changes leaving it idle will likely result in conflicts when other pull requests are merged and the need to introduce modifications in order to be able to merge.
I do not see any blocking factor to proceed with merging  and closing it. In my application which utilizes the full set of udig SDK I am using geotools 19.x over 6 months without any issues. If there are any real concerns about the RingExtractor test (IMHO these tests are wrongly implemented ) we can create a separate issue to handle them.

**Comment by fgdrf** [comment]
> We must see how we address this PR and whether we are going to merge it? Since it introduces a major number of changes leaving it idle will likely result in conflicts when other pull requests are merged and the need to introduce modifications in order to be able to merge.

Agree, however I'd like to upgrade to latest 19.x Release : 19.2 while 19.3 is comming in October this year (https://github.com/geoserver/geoserver/wiki/Release-Schedule)

> If there are any real concerns about the RingExtractor test (IMHO these tests are wrongly implemented ) we can create a separate issue to handle them.

I'm fine with it. Let's skip failing tests for now and create an issue for that. I'd suggest to add a link to issue in the comment for `@Ignore`

**Comment by fgdrf** [comment]
Looking good on Mac OS

started build on Jenkins : https://ci.eclipse.org/udig/job/uDig-PR/25/

**Comment by fgdrf** [comment]
Just on failure, just increment the minor version in test
```
java.lang.AssertionError: expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.locationtech.udig.libs.tests.GeoToolsTest.testGeoTools(GeoToolsTest.java:61)
```

**Comment by nprigour** [comment]
Minor version number in GeoToolsTest corrected! 
I performed also a rebase with master branch to resolve a conflict that existed.
For the moment, I did not disabled the RingExtractorTest since to  my local env it seems that the failing tests now pass. 
Please kick start another Jenkins build to verify this.

**Comment by nprigour** [comment]
Hi @fgdrf ,

I think it is now ready for CI testing!

**Comment by fgdrf** [comment]
CI started : https://ci.eclipse.org/udig/job/uDig-PR/26/

**Comment by nprigour** [comment]
Hmm,

I forgot to commit the manifest file after updating library versions in pom-libs.xml.
It should be OK now.
Please @fgdrf  initiate another CI run

**Comment by nprigour** [comment]
It seems that the CI build was successful and without the need to disable RingExtractor tests!!!!

**Comment by fgdrf** [comment]
@nprigour Thanks a ton for upgrading GeoTools!!

**Pull request merged**
