### PR TITLE
Safer clear with tests of null (no NPEs)

### PR DESCRIPTION
**Pull request by MSementsov-Ibk**
Signed-off-by: Michael Sementsov <michael.sementsov@ibykus.de>

### CODE REVIEW

**Comment by nprigour** [comment]
Is placement of bracket in if statement correct according to udig formatting rules?

**Comment by fgdrf** [comment]
Good point, haven’t seen this. Let’s fix it with another commit

nprigour <notifications@github.com> schrieb am Fr. 5. Okt. 2018 um 22:55:

**Comment by nprigour** [comment]
Note that similar formatting issues occurs in other PR created by @MSementsov-Ibk so it would be good to have a look over them and correct formatting before any merge to the master.

**Comment by fgdrf** [comment]
Actually he changed Eclipse settings since I noticed formating issues in
#302

However we going to review other PRs regarding formatings. Thanks for
reviewing!

nprigour <notifications@github.com> schrieb am Fr. 5. Okt. 2018 um 23:09:

**Pull request merged**
