### PR TITLE
Upgrade GeoTools 22.x

### PR DESCRIPTION
**Pull request by fgdrf**
In behalf of @egouge I created this pull-request for master

### CODE REVIEW

**Comment by nprigour** [comment]
Hi, 

May be it is worth to move to recently released geotools 22.1 (instead of 22.0) which is supposed to be more mature.
During thid upgaded we should consider: 

- fix  https://github.com/geotools/geotools/pull/2645  which will probably resolve important issue #348 
- changes applied via https://github.com/geotools/geotools/pull/2601 and https://github.com/geotools/geotools/pull/2525 which may affect udig #218 enhancement leading to certain code modifications to restore its expected behavior.

**Comment by fgdrf** [comment]
Actually @jodygarnett wrote something in GeoTools mailing list, that 22.1 is not "valid". I guess we should move on to 22.2 once it is avalable. 

> The prior 22.1 build was one of those that failed over JDK issues so we only have partially 

I'm not really sure about the statement, itf its a good idea to upgrade to 22.2 anyway:

>  I accidentally made a 22.2 release, see user list for discussion about renaming those folders to 22.2-mistake to avoid causing problems downstream

@jodygarnett can you give us any advice how to proceed with 22.x series?

**Comment by jodygarnett** [comment]
ha ha, I screwed up so bad and different development teams around the world are all confused :P

The https://sourceforge.net/projects/geotools/files/GeoTools%2022%20Releases/22.1/ release is the latest. 

I just typed the wrong version number into the release script :P

**Comment by jodygarnett** [comment]
I have updated the release announcement to help make this clear: https://geotoolsnews.blogspot.com/2019/11/geotools-221-released.html

Sorry for the trouble.

**Comment by fgdrf** [comment]
Thank you for clarification! IMO my pull for @egouge (see https://github.com/egouge/udig-platform/pull/4) is still valid (which upgrades to 22.1)

**Comment by nprigour** [comment]
Ok @fgdrf,  
I was not aware of your  latest pull to @egouge :)

**Comment by fgdrf** [comment]
forgot to mentioned yet, my fault.

@egouge Thanks for merging!

Pre-flight Test looks good (at least on windows)

nprigour <notifications@github.com> schrieb am Di. 3. Dez. 2019 um 19:32:

**Comment by fgdrf** [comment]
Cool, all active tests passed :D (see travis build)

**Pull request merged**
