### PR TITLE
Update LICENSE.txt

### PR DESCRIPTION
**Pull request by keilw**
Clarified JSR-275 License

### CODE REVIEW

**Comment by keilw** [comment]
Hi, please be aware, that the JSR-275 reference in some sources jsr-275-1.0-beta-2.jar is illegitimate and outdated, see http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22jsr-275%22. The second one "javax.measure" is correct, and JSR-275 version 0.9.3 or above matches the version used by GeoAPI 0.3 (which it seems, uDig also does use somewhere;-)

However, Eclipse IP team just asserted, the JCP Spec License was not allowed for Eclipse / LocationTech projects, therefore JSR-275 cannot be used by an Eclipse project any more.

Let me know if I can help with a replacement. As of now, the only legitimate dependency is Unit-API 0.6.1 by the same authors (lead by myself and Jean-Marie) see Orbit: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=6720

Regards,
Werner

**Comment by keilw** [comment]
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=6720

**Comment by fgdrf** [comment]
@keilw Thanks for the pull request. At the moment I'm bit confused about this dependency since it is already approved by [CQ 7583](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=7583). I saw your comments but I'm now unsure how to deal with it. Let' move discussion to mentioned CQ

**Comment by keilw** [comment]
We're trying to clarify with Mike and others, if there is a clear and sustainable understanding of what API is and where it stands for JSRs. In any case, the lady who attached the JAR to the CQ made a mistake by using a hopelessly old "Beta 2" in 2013 when the latest ever available JSR 275 version (0.9.4 or 0.9.5, they are practically the same) was out since 2010. So if you use that "Beta 2" you have an outdated and wrong version compared to e.g. GeoAPI 3 which uses the 0.9.3 version, too.

**Comment by fgdrf** [comment]
Interesting, its a transitive dependency of a GeoTools library. Going to find out, whether jsr packages are exported and where uDig is using these.. Same with gt-imagemosaic as well..

```
[INFO] +- org.geotools:gt-imagemosaic:jar:11.2:compile
[INFO] |  +- net.java.dev.jsr-275:jsr-275:jar:1.0-beta-2:compile
```

**Comment by keilw** [comment]
Do any of them implement the official GeoAPI 3.0 standard?
Its POM http://search.maven.org/#artifactdetails%7Corg.opengis%7Cgeoapi-parent%7C3.0.0%7Cpom is quite clear using javax.measure:jsr-275 in version 0.9.3.
http://mvnrepository.com/artifact/javax.measure/jsr-275/usages
shows the correct usage of JSR-275 while
http://mvnrepository.com/artifact/net.java.dev.jsr-275/jsr-275/usages
shows some (only 4) artifacts that use the outdated one by mistake or because they were written earlier.

**Comment by fgdrf** [comment]
@keilw Does it mean if ban dependency 
```
<dependency>
	<groupId>net.java.dev.jsr-275</groupId>
	<artifactId>jsr-275</artifactId>
	<version>1.0-beta-2</version>
</dependency>
```
and replace it with 

```
 <dependency>
 	<groupId>javax.measure</groupId>
 	<artifactId>jsr-275</artifactId>
 	<version>0.9.4</version>
 </dependency>
```

we would be fine? Or vise versa?

**Comment by keilw** [comment]
As of GeoAPI 3 it would be
`<dependency>
<groupId>javax.measure</groupId>
<artifactId>jsr-275</artifactId>
<version>0.9.3</version>
</dependency>`

At the moment an Eclipse CQ for JSR 363 looks promising, but you may have to wait till a new version of GeoAPI uses that instead.

**Comment by fgdrf** [comment]
Closing this issue here and waiting for IP team findings. In addtion tthe commit has never been signed anyway

**Comment by keilw** [comment]
If you're still waiting, hopefully it won't be too long till you may actually replace it with 
`dependency> <groupId>javax.measure</groupId> <artifactId>unit-api</artifactId> <version>1.0</version> </dependency>` ;-) As soon as both Eclipse and GeoAPI approve and include the new JSR this should be irrelevant anyway.

**Pull request closed without merging**
