### PR TITLE
activates (almost all) tests for FeatureTypeEditor

### PR DESCRIPTION
**Pull request by fgdrf**
See also #233

### CODE REVIEW

**Comment by fgdrf** [comment]
@nprigour can you test with changed FeatureTypeEditor? Sorry for my confusing pull request where commit 8871142bf4d54b44eed8b975bf7b0013b48cba82 forced a merge from master.

Maybe it is easier to  reset your branch hard to the lates commit you made (HEAD~2) and force a push to your remote branch. 

Would you prefer to get this pull request merged to master to verify your changes first?

**Comment by nprigour** [comment]
Hi @fgdrf ,
I am a bit confused. To which branch you are referring to reset to my master branch or to the branch related to  FeatureTypeEditor pull request enhancement?

**Comment by fgdrf** [comment]
In your branch that you were working on for the related pull request.
HTH

nprigour <notifications@github.com> schrieb am Mo. 2. Apr. 2018 um 22:31:

**Comment by nprigour** [comment]
H @fgdrf ,

I went back 2 commits and forced pushed to rewrite history to pull request #233 as you advised. Now related to this one:
How exactly am I supposed to run these test case in order verify behavior? Can you explain a bit (is it possible via maven or eclipse IDE?).

**Comment by fgdrf** [comment]
Sure! Two things to do:
* rebase your branch to latest from master, resolve conflicts of there at
any (checkout master, pull —rebase, checkout your branch, git rebase master)
* to run tests you need to build once with ‚clean install
-Pproduct,doc,test‘ from root checkout folder

Afterwards, you can run mbn clean install within the test module As long as
you haven’t changed anything in the module that’s under test. If so, run a
full build as mentioned above
HTH


nprigour <notifications@github.com> schrieb am Di. 3. Apr. 2018 um 10:50:

**Comment by nprigour** [comment]
Followed your instructions here area the results for FeatureTypeEditor tests:
Running org.locationtech.udig.ui.FeatureTypeEditorTest
```
Tests run: 7, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.746 sec - in org.locationtech.udig.ui.FeatureTypeEditorTest
testGetCreateAttributeAction(org.locationtech.udig.ui.FeatureTypeEditorTest)  Time elapsed: 0.152 sec
testCreateLabel(org.locationtech.udig.ui.FeatureTypeEditorTest)  Time elapsed: 0.1 sec
testGetDeleteAction(org.locationtech.udig.ui.FeatureTypeEditorTest)  Time elapsed: 0.103 sec
testCloseOpenDialog(org.locationtech.udig.ui.FeatureTypeEditorTest)  Time elapsed: 0.165 sec
testSetFeatureType(org.locationtech.udig.ui.FeatureTypeEditorTest)  Time elapsed: 0.093 sec
testCellModifierModify(org.locationtech.udig.ui.FeatureTypeEditorTest)  Time elapsed: 0.131 sec
testCellModifierGetValue(org.locationtech.udig.ui.FeatureTypeEditorTest) skipped
```

It seems that all active tests successfully passed.

**Comment by fgdrf** [comment]
> It seems that all active tests successfully passed.
> However why testCellModifierGetValue(org.locationtech.udig.ui.FeatureTypeEditorTest) is disabled?
> I think you can enable it just comment out the 4 lines related to editElement and cancelEditing which seems not to be needed.

I got a SWT widget disposed exception, however I haven’t found the reason and if your changes fixes it I‘m fine with it! 👍

I can merge it to master to proceed with your improvement. In this case you can enable the last test whist your suggested change. 

Many thanks for your feedback!

**Pull request merged**
