### PR TITLE
Fixed OpenStyleEditorAction to select a more appropriate StyleEditorPage

### PR DESCRIPTION
**Pull request by cmhodgson**
Changed the OpenStyleEditorAction to look through the loaded StyleEditorPage extensions instead of using Class.forName() (which wasn't working because the StyleEditorPages are loaded by a
different classloader).

Signed-off-by: Chris Hodgson <chodgson@refractions.net>

### CODE REVIEW

**Comment by cmhodgson** [comment]
I have now signed the eclipse CLA. Is there a way to redo the checks? Or do I need to redo the pull request?

**Comment by fgdrf** [comment]
Its a diff that's down below 1000 line- change. Therefore it should be
enought if you sign your commit with the -s option for git

Please reset your commit, commit again with -s and push the branch with
force-option again.

HTH


Am Mittwoch, 11. Mai 2016 schrieb Chris Hodgson :

**Comment by fgdrf** [comment]
Just saw, you signed off already. I remember there is an open issue for the
commit checks. I'm going to have a look at

--
Frank

Am Mittwoch, 11. Mai 2016 schrieb Frank Gasdorf :

**Comment by cmhodgson** [comment]
Thanks Frank just let me know if you need anything more from me.

**Comment by cmhodgson** [comment]
Let me try closing this pull request and re-opening. Now that I have signed the Eclipse CLA maybe it will work.

**Comment by cmhodgson** [comment]
OK now we're good to go!?

**Comment by cmhodgson** [comment]
Thanks Frank!

**Pull request merged**
