### PR TITLE
Calculate winding from ring.

### PR DESCRIPTION
**Pull request by akater320**
Correctly calculate the winding of triangles.

Fixes [342](https://github.com/locationtech/udig-platform/issues/342)

Signed-off-by: Adam Kater <adam.kater@gmail.com>

### CODE REVIEW

**Comment by nprigour** [comment]
Indeed the suggested commit fixes the issue mention in #342 and permits creation of holes with 3 coordinates and suppress the thrown exception.
However @akater320 would it be possible to explain a little bit the issue with the winding? Debugging I can infer that all holes are converted to CW (ClockWise) winding. Do you think that there is a particular reason for doing this or is it just an arbitrary assumption by the class creator in order all holes to have the same winding? Would there be any implication that we must be aware of?

**Comment by akater320** [comment]
Good question.
I think the author's intent was to orient the edges so that the interior of the polygon is always on the right.

But, assuming this is the correct Polygon class [com.vividsolutions.jts.geom.Polygon](https://github.com/simplegeo/jts/blob/master/src/com/vividsolutions/jts/geom/Polygon.java) the comments explicitly state that orientation of rings does not matter. There is also no guarantee that orientation is preserved.
Java 2D uses an even/odd ray-cast to determine the interior of closed Paths so orientation won't matter there either.

So, the winding direction should probably be treated as arbitrary.

**Comment by nprigour** [comment]
OK thanks for the clarification @akater320.
Now in order to finalize the issue I think (please @fgdrf  confirm) that we should add a test that verifies that correct behavior of GeometryCreationUtil when creating polygon with a hole with 3 coordinates. There is a test class GeometryCreationUtilTest in plugin org.locationtech.udig.tool.edit.tests which can be extended to include a test on that. Would it be possible to do it?

**Comment by akater320** [comment]
@nprigour Is it possible to run all of the tests at once? Or is it necessary to run each test plugin individually?

**Comment by nprigour** [comment]
What do you mean by all the tests at once? If you refer to all udig tests in the various plugins then this can be accomplished by mvn by running the following command 
mvn clean install -Pproduct,test

**Comment by akater320** [comment]
@nprigour 
Perfect! Thank you.

**Comment by fgdrf** [comment]
Just testing a maven run with test profile, if I get no failures I'll merge it

**Pull request merged**
