### PR TITLE
[#351] fixes InitMapCRS Interceptor

### PR DESCRIPTION
**Pull request by fgdrf**
If defaultCRSPreference is set and valid, do not use the CRS from first added layer.

Signed-off-by: Frank Gasdorf <fgdrf@users.sourceforge.net>

### CODE REVIEW

**Comment by fgdrf** [comment]
@nprigour Would you please have a look at the Interceptor changes? The problem is described in issue #351

**Comment by nprigour** [comment]
Hi @fgdrf ,

First of all I would like to ask why you have collocated travis build changes within the present request? Are they relevant? 

Now about the InitMapCRS Interceptor:
I review and test via the UI the proposed changes. Indeed now the behavior is as follows:

-  if -1 is set then the first layer determines the map CRS
- if a specific EPSG code is set (i.e. 4326) and is valid then the map is created with that CRS independent of the 1st added layer CRS. 
However there is still an issue:
The defaultCRSPreference  set via the Map preference  page is somewhat cached  the first time (since it is set in the field DEFAULT_CRS of the ViewportModel interface). Therefore any subsequent change via the preference page is not propagated to the ViewportModelImpl and the DEFAULT_CRS remains always to the value set the 1st time. You can verify this by changing, while udig is running, the CRS preference value to another EPSG code =2100, deleting the Map and try to load a shapefile to the LayersView. You will observe that the Map CRS will remain 4326.
A possible solution would be to not use the value DEFAULT_CRS when setting the cRS protected member in ViewportModelImpl class (as in line 91): 

       `protected CoordinateReferenceSystem cRS = DEFAULT_CRS;`

but rather modify it to something like the following:
        
        `protected CoordinateReferenceSystem cRS = ViewportModelImpl.getDefaultCRS();`

However we must also take care of other fields that dependent on DEFAULT_CRS (i.e. from a quick check there is also NIL_BBOX which is created and cached based on DEFAULT_CRS)

**Comment by fgdrf** [comment]
> First of all I would like to ask why you have collocated travis build changes within the present request? Are they relevant?

Not really but Travis is the only system we have to get feedback regarding compile / unit-test failures. Pull-Request build on ci.eclipse.org doens't work anymore..

> Now about the InitMapCRS Interceptor:
> I review and test via the UI the proposed changes. Indeed now the behavior is as follows:
> 
>     * if -1 is set then the first layer determines the map CRS
> 
>     * if a specific EPSG code is set (i.e. 4326) and is valid then the map is created with that CRS independent of the 1st added layer CRS.

Great, thanks for testing!

>       However there is still an issue:
>       The defaultCRSPreference  set via the Map preference  page is somewhat cached  the first time (since it is set in the field DEFAULT_CRS of the ViewportModel interface). Therefore any subsequent change via the preference page is not propagated to the ViewportModelImpl and the DEFAULT_CRS remains always to the value set the 1st time. You can verify this by changing, while udig is running, the CRS preference value to another EPSG code =2100, deleting the Map and try to load a shapefile to the LayersView. You will observe that the Map CRS will remain 4326.
>
>       A possible solution would be to not use the value DEFAULT_CRS when setting the cRS protected member in ViewportModelImpl class (as in line 91):
>       ```
>        `protected CoordinateReferenceSystem cRS = DEFAULT_CRS;`
>       ```
> but rather modify it to something like the following:
> 
> ```
>     `protected CoordinateReferenceSystem cRS = ViewportModelImpl.getDefaultCRS();`
> ```
> 
> However we must also take care of other fields that dependent on DEFAULT_CRS (i.e. from a quick check there is also NIL_BBOX which is created and cached based on DEFAULT_CRS)

Sounds like another issue independently from this changeset for LayerInterceptor. Would you help providing a fix for this problem to referenced branch as a pull request? So we could join forces to fix both problems ;)

**Comment by nprigour** [comment]
Hi @fgdrf ,

I added a PR in your local fgdrf:ISSUE_351_fix  branch with a proposed solution

**Pull request merged**
