### PR TITLE
[HK] fix EMF Model (jts) and (re-)generated Code

### PR DESCRIPTION
**Pull request by fgdrf**
It changes namespace from com.vividsolution to org.locationtech in EMF Model.

Fixed Model regarding:
* runtime version
* emf runtime version (matches emf version from target-definition)
* several formatting settings 

Signed-off-by: Frank Gasdorf <fgdrf@users.sourceforge.net>

### CODE REVIEW

**Review by erdalkaraca — APPROVED** [review]
most (or all) of the code is due to code generation and/or formatting... I only reviewed the ecore/genmodel files

**Comment by fgdrf** [comment]
> most (or all) of the code is due to code generation and/or formatting... I only reviewed the ecore/genmodel files

@erdalkaraca Great, thanks for your review . I stumbled about MapImpl.getColorScheme() method where regenerated code looked like this:

`  /**
     *  
     * @generated
     */
    @Override
    public ColourScheme getColourScheme() {
        return colourScheme;
    }
`

and therefore I've added a **NOT** right behind `@generated` to avoid removing lazy initialization code.

**Comment by erdalkaraca** [comment]
In that case I would also comment why you need lazy initialization. If I remember correctly, some code in uDig uses OS resources that should not be initialized immediately

> > most (or all) of the code is due to code generation and/or formatting... I only reviewed the ecore/genmodel files
> 
> @erdalkaraca Great, thanks for your review . I stumbled about MapImpl.getColorScheme() method where regenerated code looked like this:
> 
> ```
>    /**
>      *  
>      * @generated
>      */
>     @Override
>     public ColourScheme getColourScheme() {
>         return colourScheme;
>     }
> ```
> 
> and therefore I've added a **NOT** right behind `@generated` to avoid removing lazy initialization code. Now it looks as follows:
> 
> ```
>     /**
>      *  
>      * @generated NOT
>      */
>     @Override
>     public ColourScheme getColourScheme() {
>         if (colourScheme == null) {
>             colourScheme = ColourScheme.getDefault(getColorPalette());
>         }
>         return colourScheme;
>     }
> ```

**Comment by fgdrf** [comment]
> MapImpl

I had some trouble initializing Maps in a multi-threaded environment and provided a patch in the past: https://github.com/locationtech/udig-platform/commit/c16617d2bb0e874aa4acd3f39288ead1ee71e327#diff-27f9c02051f99a7cdd33a9d8c0fcc5b38249aa00fdab87c5f2e630b411ee5cab

Question: Is it possible to define it in the model where and when initializing Content? Would it make sense to move the initialization to `org.locationtech.udig.project.internal.impl.ProjectFactoryImpl.createMap()` rather than in the MapImpl object itself?

**Comment by erdalkaraca** [comment]
The factories just call the constructors, so there would be no benefit here. It is also not recommended to have code in the constructor of the generated classes. You can add the simple code in the ecore file by defining an ecore genmodel annotation on the attribute.

> > MapImpl
> 
> I had some trouble initializing Maps in a multi-threaded environment and provided a patch in the past: [c16617d#diff-27f9c02051f99a7cdd33a9d8c0fcc5b38249aa00fdab87c5f2e630b411ee5cab](https://github.com/locationtech/udig-platform/commit/c16617d2bb0e874aa4acd3f39288ead1ee71e327#diff-27f9c02051f99a7cdd33a9d8c0fcc5b38249aa00fdab87c5f2e630b411ee5cab)
> 
> Question: Is it possible to define it in the model where and when initializing Content? Would it make sense to move the initialization to `org.locationtech.udig.project.internal.impl.ProjectFactoryImpl.createMap()` rather than in the MapImpl object itself?

**Comment by fgdrf** [comment]
> The factories just call the constructors, so there would be no benefit here. It is also not recommended to have code in the constructor of the generated classes. You can add the simple code in the ecore file by defining an ecore genmodel annotation on the attribute.

Cool, had a look at and tried it:

```
    <eOperations name="getColourSchema" eType="#//ColourScheme">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="if (colourScheme == null) {&#xA;            colourScheme = ColourScheme.getDefault(getColorPalette());&#xA;}&#xA;return colourScheme;"/>
      </eAnnotations>
    </eOperations>
```

makes the trick and I could remove "NOT" from @generated. Question for me: Code is persisted in the model and might not fit PMD/Spotbugs rules in the future anymore. Developers need to know that is comming from the model, might reduce maintainability.

And las but not least, I guess its not a good practice to have some methodes bodies in the model and others implemented after generation of code and manually edited.

I guess for now I'll leave it as it is in the pull request but I learned how to do it the other way. Thanks for that!

> 
> > > MapImpl
> > 
> > 
> > I had some trouble initializing Maps in a multi-threaded environment and provided a patch in the past: [c16617d#diff-27f9c02051f99a7cdd33a9d8c0fcc5b38249aa00fdab87c5f2e630b411ee5cab](https://github.com/locationtech/udig-platform/commit/c16617d2bb0e874aa4acd3f39288ead1ee71e327#diff-27f9c02051f99a7cdd33a9d8c0fcc5b38249aa00fdab87c5f2e630b411ee5cab)
> > Question: Is it possible to define it in the model where and when initializing Content? Would it make sense to move the initialization to `org.locationtech.udig.project.internal.impl.ProjectFactoryImpl.createMap()` rather than in the MapImpl object itself?

**Pull request merged**
